name: Upload Image

on:
  workflow_run:
    workflows: ["Update Language Stats"]  # The name of the previous workflow
    types:  
      - completed  # Only run when the previous workflow has completed
  workflow_dispatch:

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v3
        with:
          repository: Redck9/Most-Used-Language-Card  # Your public repository name
          token: ${{ secrets.GH_TOKEN }}  # Use the token to access the public repo

      - name: Copy image to public repository
        run: |
          cp ../Most-Used-Languages-Git/images/language_stats.png ./images/language_stats.png

      - name: Commit and push the updated image
        run: |
          git config --local user.name "Redck9"
          git config --local user.email "rpedroslb@gmail.com"
          git add images/language_stats.png
          git commit -m "Update language stats image"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
